/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface DrAmbulanceWlList {
    }
}
declare global {
    interface HTMLDrAmbulanceWlListElement extends Components.DrAmbulanceWlList, HTMLStencilElement {
    }
    var HTMLDrAmbulanceWlListElement: {
        prototype: HTMLDrAmbulanceWlListElement;
        new (): HTMLDrAmbulanceWlListElement;
    };
    interface HTMLElementTagNameMap {
        "dr-ambulance-wl-list": HTMLDrAmbulanceWlListElement;
    }
}
declare namespace LocalJSX {
    interface DrAmbulanceWlList {
    }
    interface IntrinsicElements {
        "dr-ambulance-wl-list": DrAmbulanceWlList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "dr-ambulance-wl-list": LocalJSX.DrAmbulanceWlList & JSXBase.HTMLAttributes<HTMLDrAmbulanceWlListElement>;
        }
    }
}
